// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6aJg_l1sDfF3B1T6RmHQXJTegYjvhbY',
    appId: '1:213494682617:web:60d7cbe7ba914fd751a328',
    messagingSenderId: '213494682617',
    projectId: 'movie-playlist-2af8e',
    authDomain: 'movie-playlist-2af8e.firebaseapp.com',
    storageBucket: 'movie-playlist-2af8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdU6dNg-hQOviw5a8oeXdtlFK41RKby-Q',
    appId: '1:213494682617:android:41e44ea6d409d3c751a328',
    messagingSenderId: '213494682617',
    projectId: 'movie-playlist-2af8e',
    storageBucket: 'movie-playlist-2af8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMMHz6I__Go1NJQQ3RP13iML86D14_fDs',
    appId: '1:213494682617:ios:54d5779960e20f0551a328',
    messagingSenderId: '213494682617',
    projectId: 'movie-playlist-2af8e',
    storageBucket: 'movie-playlist-2af8e.appspot.com',
    iosClientId: '213494682617-4cau4ftfvde02g0is91soojcm4sd0e5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviePlaylist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMMHz6I__Go1NJQQ3RP13iML86D14_fDs',
    appId: '1:213494682617:ios:54d5779960e20f0551a328',
    messagingSenderId: '213494682617',
    projectId: 'movie-playlist-2af8e',
    storageBucket: 'movie-playlist-2af8e.appspot.com',
    iosClientId: '213494682617-4cau4ftfvde02g0is91soojcm4sd0e5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviePlaylist',
  );
}
